spring:
  zipkin:
    base-url: http://localhost:8220
  sleuth:
    sampler:
      percentage: 1.0

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework: INFO
    org.springframework.web.servlet.DispatcherServlet: DUBUG 

git:
  microservice:
    guaranty:
      web:
        test: "test for bus new"
